# Project 1

**Team Members:** Brock Hoover

**Date Submitted For Review:** February 3rd, 2026

**Submitted to: Dr. Lane**

**Client Information:** Our client is the UNMC Water, Climate and Health Group, which is using data collected from AirPurple where a .csv has been made with the data.

**Project Goals:** The goals of this project are to find the 5 locations in Nebraska with the highest mean and median concentrations of VOC, PM 2.5 and PM 10.0, when and where the maximum values occurred, and whether humidity and temperature affect air quality. The client has also asked for the temperature to be categorized

**Project Tasks:** For this project, we will need to use the aggregate, group, and filter functions in python to find the monitors with the project goal data. We will then need to use functions in python to assign each temparature value to a certain category, and use some sort of graphing/correlation function to see if temperature matters

## **Project Instructions:**

## Step 1: 
first, we import pandas and load the data, the file used is AirQuality_Daily_StudentVersion.csv, so this will need to be changed to the respective file 
when this code is being ran

In [19]:
#Import Pandas
import pandas as pd
#Read Data into Pandas
air_data = pd.read_csv("AirQuality_Daily_StudentVersion.csv")
#Print data (for verification that the data has been imported correctly and the correct file has been importd
print(air_data)

           date  monitor_index   humidity    pressure  temperature  \
0     2/23/2024         195089  14.377667  912.884333    62.266667
1     2/23/2024         195365  12.223600  926.403000    71.193400
2     2/23/2024         195541  20.095750  905.670750    61.008250
3     2/24/2024         195089  25.368000  911.708833    51.462458
4     2/24/2024         195365  23.703083  925.282125    56.818208
...         ...            ...        ...         ...          ...
8296  3/24/2025         195373  23.636208  915.998292    61.489083
8297  3/24/2025         195379  28.043545  954.294546    66.009182
8298  3/24/2025         195383  31.451375  936.556583    55.752792
8299  3/24/2025         195385        NaN         NaN          NaN
8300  3/24/2025         195541  20.494500  901.484750    61.222167

             voc  analog_input  pm2.5_alt  pm1.0_atm  pm2.5_atm  pm10.0_atm  \
0      51.998667      0.051333   0.100000   0.000000   0.002500    0.039667
1      64.920800      0.000000   0.180000   0.004800   0.020000    0.176000
2      68.307000      0.020000   0.162500   0.004125   0.014812    0.063937
3      91.176750      0.052667   0.437500   0.099542   0.170667    0.355208
4     107.863708      0.000000   0.475000   0.099208   0.231687    0.548583
...          ...           ...        ...        ...        ...         ...
8296  421.493750      0.020000   0.762500   0.486583   0.830021    1.416125
8297  301.074800      0.000000   0.800000   5.625545   5.873364    6.056773
8298  353.478000      0.050000   0.575000   0.267500   0.478375    0.818146
8299         NaN      0.010000   0.970833   0.739500   1.088604    1.340563
8300  485.556417      0.020000   0.554167   0.132083   0.340417    0.737375

      sensor.latitude  sensor.longitude  sensor.altitude  \
0           40.050922       -101.533570             3005
1           40.200330       -100.639885             2576
2           41.128284       -101.720220             3220
3           40.050922       -101.533570             3005
4           40.200330       -100.639885             2576
...               ...               ...              ...
8296        41.148170       -100.761800             2800
8297        40.877007        -97.579445             1639
8298        41.779380        -99.138040             2174
8299        40.019714        -98.071840             1597
8300        41.128284       -101.720220             3220

                                            sensor.name
0                                      Swnphd-Benklemen
1                                         Swnphd-mccook
2                                       Swnphd-ogallala
3                                      Swnphd-Benklemen
4                                         Swnphd-mccook
...                                                 ...
8296                                WCDHD City Building
8297                                           FCHD-YPS
8298                Loup Basin Public Health Department
8299  South Heartland District Health Dept. Superior...
8300                                    Swnphd-ogallala

[8301 rows x 15 columns]

## Step 2:
Next, we then find the 5 locations with the highest mean and median in the following categories: VOC, PM2.5 PM 10.0

In [42]:
voc_stats = air_data.groupby('sensor.name')['voc'].agg(['mean','median'])
pm25_stats = air_data.groupby('sensor.name')['pm2.5_atm'].agg(['mean','median'])
pm10_stats = air_data.groupby('sensor.name')['pm10.0_atm'].agg(['mean','median'])

These code lines were refined using input from Gemini Model 3 Pro, the output can be seen here: https://gemini.google.com/share/aa0454b1e8f0

### Categories: Run the respective sections you want to run, by hitting select for the code within the section

All of the Top 5 category codes were modified using feedback from Gemini Model 3 Pro, the output can be seen here: https://gemini.google.com/share/aa0454b1e8f0

**Top 5 Median VOC:**

In [43]:
voc_median5 = voc_stats.sort_values(by='median',ascending=False).head(5)
voc_median5

                                             mean      median
sensor.name
Swnphd-ogallala                        399.434240  423.082292
Swnphd-mccook                          353.941581  381.468479
Three Rivers Public Health Department  370.216208  376.810167
FCHD-YPS                               372.462720  375.383500
ELVPHD Norfolk HD 4                    360.833744  368.580500

**Top 5 Mean VOC:**

In [44]:
voc_mean5 = voc_stats.sort_values(by='mean',ascending=False).head(5)
voc_mean5

                                             mean      median
sensor.name
Swnphd-ogallala                        399.434240  423.082292
FCHD-YPS                               372.462720  375.383500
Three Rivers Public Health Department  370.216208  376.810167
ELVPHD Norfolk HD 4                    360.833744  368.580500
Swnphd-mccook                          353.941581  381.468479

**Top 5 Median PM 2.5:**

In [45]:
pm25_median5 = pm25_stats.sort_values(by='median',ascending=False).head(5)
pm25_median5

                                                          mean     median
sensor.name
Broken Bow                                          928.710593  36.050240
#16 - Richardson County Courthouse                  700.127342  11.977344
#18 - Southeast District Health Department- Tec...  613.175352  10.322875
ELVPHD Norfolk HD 4                                  13.369492   9.706229
ELVPHD Wisner HD 5                                   11.154420   8.464583

**Top 5 Mean PM 2.5:**

In [46]:
pm25_mean5 = pm25_stats.sort_values(by='mean',ascending=False).head(5)
pm25_mean5

                                                          mean     median
sensor.name
Broken Bow                                          928.710593  36.050240
#16 - Richardson County Courthouse                  700.127342  11.977344
#18 - Southeast District Health Department- Tec...  613.175352  10.322875
NCDHD O'Neill #11                                   164.495078   7.251208
Swnphd-mccook                                       123.011622   4.582281

**Top 5 Median PM 10:**

In [62]:
pm10_median5 = pm10_stats.sort_values(by='median',ascending=False).head(5)
pm10_median5

                                                          mean     median
sensor.name
Broken Bow                                          929.678512  43.179094
#16 - Richardson County Courthouse                  701.632446  13.305615
ELVPHD Norfolk HD 4                                  15.969341  11.474708
#18 - Southeast District Health Department- Tec...  614.227248  11.433729
ELVPHD Wisner HD 5                                   14.462116  10.935958

**Top 5 Mean PM 10:**

In [48]:
pm10_mean5 = pm10_stats.sort_values(by='mean',ascending=False).head(5)
pm10_mean5

                                                          mean     median
sensor.name
Broken Bow                                          929.678512  43.179094
#16 - Richardson County Courthouse                  701.632446  13.305615
#18 - Southeast District Health Department- Tec...  614.227248  11.433729
NCDHD O'Neill #11                                   166.132578   8.427437
Swnphd-mccook                                       124.227336   5.372073

## Step 2:

We need to find the max days where things occurred, this can be done similarly to step 1

In [58]:
max_voc = air_data.sort_values(by='voc', ascending=False)[['date', 'sensor.name', 'voc', 'sensor.latitude', 'sensor.longitude']]
max_pm25 = air_data.sort_values(by='pm2.5_atm', ascending=False)[['date', 'sensor.name', 'pm2.5_atm', 'sensor.latitude', 'sensor.longitude']]
max_pm10 = air_data.sort_values(by='pm10.0_atm', ascending=False)[['date', 'sensor.name', 'pm10.0_atm', 'sensor.latitude', 'sensor.longitude']]

**Max Voc:**

In [59]:
max_voc.head(1)

,date,sensor.name,voc,sensor.latitude,sensor.longitude
2391,6/24/2024,Swnphd-ogallala,1209.931571,41.128284,-101.72022

**Max PM 2.5:**

In [60]:
max_pm25.head(1)

,date,sensor.name,pm2.5_atm,sensor.latitude,sensor.longitude
7561,2/18/2025,#16 - Richardson County Courthouse,3782.823313,40.0622,-95.6024

**Max PM 10.0:**

In [61]:
max_pm10.head(1)

,date,sensor.name,pm10.0_atm,sensor.latitude,sensor.longitude
7561,2/18/2025,#16 - Richardson County Courthouse,3784.682542,40.0622,-95.6024

## Step 3:
Next, we then find the effect of temperature, humidity, and altitude on air quality, functions are used on the air data to accomplish this task.

**Temperature Categorization:**

Temperature was categorized according to project instructions, with a temperature below 32 being designated as freezing, a temperature between 32 and 50 being designated as cool, and a temperature between 51 and 70 being designated as hot, and any temperature higher than 70 being designated as hot

In [9]:
def cat_temperature(temperature):
    if temperature < 32:
        return 'Below Freezing'
    elif 32 <= temperature <= 50:
        return 'Cool'
    elif 51 <= temperature <= 70:
        return 'Warm'
    else:
        return 'Hot'
air_data['cat_temperature'] = air_data['temperature'].apply(cat_temperature)

air_dataS

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name,cat_temperature
0,2/23/2024,195089,14.377667,912.884333,62.266667,51.998667,0.051333,0.100000,0.000000,0.002500,0.039667,40.050922,-101.533570,3005,Swnphd-Benklemen,Warm
1,2/23/2024,195365,12.223600,926.403000,71.193400,64.920800,0.000000,0.180000,0.004800,0.020000,0.176000,40.200330,-100.639885,2576,Swnphd-mccook,Hot
2,2/23/2024,195541,20.095750,905.670750,61.008250,68.307000,0.020000,0.162500,0.004125,0.014812,0.063937,41.128284,-101.720220,3220,Swnphd-ogallala,Warm
3,2/24/2024,195089,25.368000,911.708833,51.462458,91.176750,0.052667,0.437500,0.099542,0.170667,0.355208,40.050922,-101.533570,3005,Swnphd-Benklemen,Warm
4,2/24/2024,195365,23.703083,925.282125,56.818208,107.863708,0.000000,0.475000,0.099208,0.231687,0.548583,40.200330,-100.639885,2576,Swnphd-mccook,Warm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8296,3/24/2025,195373,23.636208,915.998292,61.489083,421.493750,0.020000,0.762500,0.486583,0.830021,1.416125,41.148170,-100.761800,2800,WCDHD City Building,Warm
8297,3/24/2025,195379,28.043545,954.294546,66.009182,301.074800,0.000000,0.800000,5.625545,5.873364,6.056773,40.877007,-97.579445,1639,FCHD-YPS,Warm
8298,3/24/2025,195383,31.451375,936.556583,55.752792,353.478000,0.050000,0.575000,0.267500,0.478375,0.818146,41.779380,-99.138040,2174,Loup Basin Public Health Department,Warm
8299,3/24/2025,195385,NaN,NaN,NaN,NaN,0.010000,0.970833,0.739500,1.088604,1.340563,40.019714,-98.071840,1597,South Heartland District Health Dept. Superior...,Hot
8300,3/24/2025,195541,20.494500,901.484750,61.222167,485.556417,0.020000,0.554167,0.132083,0.340417,0.737375,41.128284,-101.720220,3220,Swnphd-ogallala,Warm

**Humidity Categorization:**

Humidity was categorized by the requested project instructions, with a humidity being considered low if the relative humidity was below 50, high if between 50 and 80, and very high if above 80

In [10]:
def cat_humidity(humidity):
    if humidity < 50:
        return 'Low'
    elif 50 <= humidity <= 80:
        return 'High'
    else:
        return 'Very High'
air_data['cat_humidity'] = air_data['humidity'].apply(cat_humidity)

air_data

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name,cat_temperature,cat_humidity
0,2/23/2024,195089,14.377667,912.884333,62.266667,51.998667,0.051333,0.100000,0.000000,0.002500,0.039667,40.050922,-101.533570,3005,Swnphd-Benklemen,Warm,Low
1,2/23/2024,195365,12.223600,926.403000,71.193400,64.920800,0.000000,0.180000,0.004800,0.020000,0.176000,40.200330,-100.639885,2576,Swnphd-mccook,Hot,Low
2,2/23/2024,195541,20.095750,905.670750,61.008250,68.307000,0.020000,0.162500,0.004125,0.014812,0.063937,41.128284,-101.720220,3220,Swnphd-ogallala,Warm,Low
3,2/24/2024,195089,25.368000,911.708833,51.462458,91.176750,0.052667,0.437500,0.099542,0.170667,0.355208,40.050922,-101.533570,3005,Swnphd-Benklemen,Warm,Low
4,2/24/2024,195365,23.703083,925.282125,56.818208,107.863708,0.000000,0.475000,0.099208,0.231687,0.548583,40.200330,-100.639885,2576,Swnphd-mccook,Warm,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8296,3/24/2025,195373,23.636208,915.998292,61.489083,421.493750,0.020000,0.762500,0.486583,0.830021,1.416125,41.148170,-100.761800,2800,WCDHD City Building,Warm,Low
8297,3/24/2025,195379,28.043545,954.294546,66.009182,301.074800,0.000000,0.800000,5.625545,5.873364,6.056773,40.877007,-97.579445,1639,FCHD-YPS,Warm,Low
8298,3/24/2025,195383,31.451375,936.556583,55.752792,353.478000,0.050000,0.575000,0.267500,0.478375,0.818146,41.779380,-99.138040,2174,Loup Basin Public Health Department,Warm,Low
8299,3/24/2025,195385,NaN,NaN,NaN,NaN,0.010000,0.970833,0.739500,1.088604,1.340563,40.019714,-98.071840,1597,South Heartland District Health Dept. Superior...,Hot,Very High
8300,3/24/2025,195541,20.494500,901.484750,61.222167,485.556417,0.020000,0.554167,0.132083,0.340417,0.737375,41.128284,-101.720220,3220,Swnphd-ogallala,Warm,Low

**Altitude Categorization:**

Nebraska doesn't have any extremely low or high altitudes, and the project requests don't ask for specific bounds. The lowest point in Nebraska is at 840 feet above sea level, and the highest point is 5,242 feet above sea level (which was found from https://nebraskalegislature.gov/pdf/bluebook/25-37.pdf). Setting ranges of 800 to 2300 feet, 2300 feet to 3800 feet, and 3800 to 5300 feet should allow us to get a good idea of how relative altitude in Nebraska could affect air quality

In [11]:
def cat_altitude(sensoraltitude):
    if 800 <= sensoraltitude < 2300:
        return 'Relative Low'
    elif 2300 <= sensoraltitude <= 3800:
        return 'Relative Medium'
    else:
        return 'Relative High'
air_data['cat_altitude'] = air_data['sensor.altitude'].apply(cat_altitude)

air_data

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name,cat_temperature,cat_humidity,cat_altitude
0,2/23/2024,195089,14.377667,912.884333,62.266667,51.998667,0.051333,0.100000,0.000000,0.002500,0.039667,40.050922,-101.533570,3005,Swnphd-Benklemen,Warm,Low,Relative Medium
1,2/23/2024,195365,12.223600,926.403000,71.193400,64.920800,0.000000,0.180000,0.004800,0.020000,0.176000,40.200330,-100.639885,2576,Swnphd-mccook,Hot,Low,Relative Medium
2,2/23/2024,195541,20.095750,905.670750,61.008250,68.307000,0.020000,0.162500,0.004125,0.014812,0.063937,41.128284,-101.720220,3220,Swnphd-ogallala,Warm,Low,Relative Medium
3,2/24/2024,195089,25.368000,911.708833,51.462458,91.176750,0.052667,0.437500,0.099542,0.170667,0.355208,40.050922,-101.533570,3005,Swnphd-Benklemen,Warm,Low,Relative Medium
4,2/24/2024,195365,23.703083,925.282125,56.818208,107.863708,0.000000,0.475000,0.099208,0.231687,0.548583,40.200330,-100.639885,2576,Swnphd-mccook,Warm,Low,Relative Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8296,3/24/2025,195373,23.636208,915.998292,61.489083,421.493750,0.020000,0.762500,0.486583,0.830021,1.416125,41.148170,-100.761800,2800,WCDHD City Building,Warm,Low,Relative Medium
8297,3/24/2025,195379,28.043545,954.294546,66.009182,301.074800,0.000000,0.800000,5.625545,5.873364,6.056773,40.877007,-97.579445,1639,FCHD-YPS,Warm,Low,Relative Low
8298,3/24/2025,195383,31.451375,936.556583,55.752792,353.478000,0.050000,0.575000,0.267500,0.478375,0.818146,41.779380,-99.138040,2174,Loup Basin Public Health Department,Warm,Low,Relative Low
8299,3/24/2025,195385,NaN,NaN,NaN,NaN,0.010000,0.970833,0.739500,1.088604,1.340563,40.019714,-98.071840,1597,South Heartland District Health Dept. Superior...,Hot,Very High,Relative Low
8300,3/24/2025,195541,20.494500,901.484750,61.222167,485.556417,0.020000,0.554167,0.132083,0.340417,0.737375,41.128284,-101.720220,3220,Swnphd-ogallala,Warm,Low,Relative Medium

**Unhealthy pm_2.5 and pm_10.0:**

AQI health risks were found from the EPA AQI Document that can be found on Canvas. For PM2.5 and PM10.0, the unhealthy risk for sensitive populations was found to be over 35.5 and over 155 respectively.

In [22]:
pm25_risk = air_data[air_data['pm2.5_atm'] >= 35.5]
unhealthy_riskpm25 = pm25_risk[['date', 'sensor.name', 'pm2.5_atm','cat_temperature','sensor.latitude', 'sensor.longitude','cat_humidity','cat_altitude']].sort_values('pm2.5_atm', ascending=False)
unhealthy_riskpm25.head(50)

,date,sensor.name,pm2.5_atm,cat_temperature,sensor.latitude,sensor.longitude,cat_humidity,cat_altitude
7561,2/18/2025,#16 - Richardson County Courthouse,3782.823313,Hot,40.062200,-95.602400,Very High,Relative Low
7583,2/19/2025,#16 - Richardson County Courthouse,3401.999333,Hot,40.062200,-95.602400,Very High,Relative Low
7605,2/20/2025,#16 - Richardson County Courthouse,3243.746646,Hot,40.062200,-95.602400,Very High,Relative Low
6962,1/21/2025,#16 - Richardson County Courthouse,3209.817146,Hot,40.062200,-95.602400,Very High,Relative Low
7572,2/18/2025,Broken Bow,3205.868854,Below Freezing,41.396297,-99.645035,Low,Relative Medium
7616,2/20/2025,Broken Bow,3179.970687,Below Freezing,41.396297,-99.645035,Low,Relative Medium
7594,2/19/2025,Broken Bow,3178.763917,Below Freezing,41.396297,-99.645035,Low,Relative Medium
6952,1/20/2025,Broken Bow,3087.149167,Below Freezing,41.396297,-99.645035,Low,Relative Medium
7429,2/12/2025,#16 - Richardson County Courthouse,3079.773604,Hot,40.062200,-95.602400,Very High,Relative Low
7573,2/18/2025,Swnphd-mccook,3053.114292,Below Freezing,40.200330,-100.639885,Low,Relative Medium
6636,1/5/2025,#16 - Richardson County Courthouse,3027.666146,Hot,40.062200,-95.602400,Very High,Relative Low
7617,2/20/2025,Swnphd-mccook,3017.204604,Below Freezing,40.200330,-100.639885,Low,Relative Medium
7595,2/19/2025,Swnphd-mccook,2995.316625,Below Freezing,40.200330,-100.639885,Low,Relative Medium
7570,2/18/2025,#18 - Southeast District Health Department- Te...,2987.467563,Below Freezing,40.368360,-96.196014,Low,Relative Low
6921,1/19/2025,#16 - Richardson County Courthouse,2948.259688,Hot,40.062200,-95.602400,Very High,Relative Low
6942,1/20/2025,#16 - Richardson County Courthouse,2921.216354,Hot,40.062200,-95.602400,Very High,Relative Low
7451,2/13/2025,#16 - Richardson County Courthouse,2877.522438,Hot,40.062200,-95.602400,Very High,Relative Low
6931,1/19/2025,Broken Bow,2873.059583,Below Freezing,41.396297,-99.645035,Low,Relative Medium
7539,2/17/2025,#16 - Richardson County Courthouse,2865.957083,Hot,40.062200,-95.602400,Very High,Relative Low
7627,2/21/2025,#16 - Richardson County Courthouse,2849.724292,Hot,40.062200,-95.602400,Very High,Relative Low
7528,2/16/2025,Broken Bow,2840.198979,Below Freezing,41.396297,-99.645035,Low,Relative Medium
7517,2/16/2025,#16 - Richardson County Courthouse,2810.763333,Hot,40.062200,-95.602400,Very High,Relative Low
7441,2/12/2025,Swnphd-mccook,2784.864979,Below Freezing,40.200330,-100.639885,Low,Relative Medium
6655,1/6/2025,#16 - Richardson County Courthouse,2777.399313,Hot,40.062200,-95.602400,Very High,Relative Low
7407,2/11/2025,#16 - Richardson County Courthouse,2775.248313,Hot,40.062200,-95.602400,Very High,Relative Low
7462,2/13/2025,Broken Bow,2769.063167,Below Freezing,41.396297,-99.645035,Low,Relative Medium
7592,2/19/2025,#18 - Southeast District Health Department- Te...,2764.382250,Below Freezing,40.368360,-96.196014,Low,Relative Low
6972,1/21/2025,Broken Bow,2754.137604,Below Freezing,41.396297,-99.645035,Low,Relative Medium
7463,2/13/2025,Swnphd-mccook,2736.564521,Below Freezing,40.200330,-100.639885,Low,Relative Medium
7418,2/11/2025,Broken Bow,2735.257354,Below Freezing,41.396297,-99.645035,Low,Relative Medium
7614,2/20/2025,#18 - Southeast District Health Department- Te...,2727.113500,Below Freezing,40.368360,-96.196014,Low,Relative Low
7440,2/12/2025,Broken Bow,2706.402708,Below Freezing,41.396297,-99.645035,Low,Relative Medium
7550,2/17/2025,Broken Bow,2682.609542,Below Freezing,41.396297,-99.645035,Low,Relative Medium
7460,2/13/2025,#18 - Southeast District Health Department- Te...,2682.460042,Below Freezing,40.368360,-96.196014,Low,Relative Low
6645,1/5/2025,Broken Bow,2671.969104,Below Freezing,41.396297,-99.645035,High,Relative Medium
7636,2/21/2025,#18 - Southeast District Health Department- Te...,2671.549875,Below Freezing,40.368360,-96.196014,Low,Relative Low
6664,1/6/2025,Broken Bow,2661.166458,Below Freezing,41.396297,-99.645035,Low,Relative Medium
6695,1/8/2025,#16 - Richardson County Courthouse,2660.962146,Hot,40.062200,-95.602400,Very High,Relative Low
7473,2/14/2025,#16 - Richardson County Courthouse,2642.719313,Hot,40.062200,-95.602400,Very High,Relative Low
6675,1/7/2025,#16 - Richardson County Courthouse,2638.205313,Hot,40.062200,-95.602400,Very High,Relative Low
6176,12/13/2024,#16 - Richardson County Courthouse,2636.834354,Hot,40.062200,-95.602400,Very High,Relative Low
6818,1/14/2025,#16 - Richardson County Courthouse,2627.851229,Hot,40.062200,-95.602400,Very High,Relative Low
7254,2/4/2025,#16 - Richardson County Courthouse,2618.688542,Hot,40.062200,-95.602400,Very High,Relative Low
6900,1/18/2025,#16 - Richardson County Courthouse,2618.362313,Hot,40.062200,-95.602400,Very High,Relative Low
6797,1/13/2025,#16 - Richardson County Courthouse,2607.493167,Hot,40.062200,-95.602400,Very High,Relative Low
6616,1/4/2025,#16 - Richardson County Courthouse,2606.781167,Hot,40.062200,-95.602400,Very High,Relative Low
7438,2/12/2025,#18 - Southeast District Health Department- Te...,2576.454583,Below Freezing,40.368360,-96.196014,Low,Relative Low
6156,12/12/2024,#16 - Richardson County Courthouse,2575.477771,Hot,40.062200,-95.602400,Very High,Relative Low
6715,1/9/2025,#16 - Richardson County Courthouse,2563.256000,Hot,40.062200,-95.602400,Very High,Relative Low
7638,2/21/2025,Broken Bow,2561.850938,Below Freezing,41.396297,-99.645035,Low,Relative Medium

In [20]:
pm10_risk = air_data[air_data['pm10.0_atm'] >= 155]
unhealthy_riskpm10 = pm10_risk[['date', 'sensor.name', 'pm10.0_atm','sensor.latitude', 'sensor.longitude','cat_temperature','cat_humidity','cat_altitude']].sort_values('pm10.0_atm', ascending=False)
unhealthy_riskpm10.head(50)

,date,sensor.name,pm10.0_atm,sensor.latitude,sensor.longitude,cat_temperature,cat_humidity,cat_altitude
7561,2/18/2025,#16 - Richardson County Courthouse,3784.682542,40.062200,-95.602400,Hot,Very High,Relative Low
7583,2/19/2025,#16 - Richardson County Courthouse,3403.435958,40.062200,-95.602400,Hot,Very High,Relative Low
7605,2/20/2025,#16 - Richardson County Courthouse,3245.613354,40.062200,-95.602400,Hot,Very High,Relative Low
6962,1/21/2025,#16 - Richardson County Courthouse,3211.046813,40.062200,-95.602400,Hot,Very High,Relative Low
7572,2/18/2025,Broken Bow,3206.779708,41.396297,-99.645035,Below Freezing,Low,Relative Medium
7616,2/20/2025,Broken Bow,3182.551396,41.396297,-99.645035,Below Freezing,Low,Relative Medium
7594,2/19/2025,Broken Bow,3179.655896,41.396297,-99.645035,Below Freezing,Low,Relative Medium
6952,1/20/2025,Broken Bow,3088.053896,41.396297,-99.645035,Below Freezing,Low,Relative Medium
7429,2/12/2025,#16 - Richardson County Courthouse,3081.850688,40.062200,-95.602400,Hot,Very High,Relative Low
7573,2/18/2025,Swnphd-mccook,3054.484250,40.200330,-100.639885,Below Freezing,Low,Relative Medium